classDiagram
    class Permission {
        id : AutoField
        name : CharField
        content_type : ForeignKey
        codename : CharField
    }
    class Group {
        id : AutoField
        name : CharField
    }
    class User {
        id : AutoField
        password : CharField
        last_login : DateTimeField
        is_superuser : BooleanField
        username : CharField
        first_name : CharField
        last_name : CharField
        email : CharField
        is_staff : BooleanField
        is_active : BooleanField
        date_joined : DateTimeField
    }
    Permission "*" }o--o{ "*" Group : "group"
    Permission "*" }o--o{ "*" User : "user"
    Group "*" }o--o{ "*" User : "user"
    Group "*" }o--o{ "*" Permission : "permissions"
    User "*" }o--o{ "*" Group : "groups"
    User "*" }o--o{ "*" Permission : "user_permissions"